### PR TITLE
feat: Add contact link to About page, resolve #37

### LINKED ISSUE #37: 🚀 Feature: add contact link
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Let's add a "get in touch" section to the about page, right above the info about the website, which has a mailto link for phillyjs@joewoods.dev:

# Get in touch

You can reach out to [Joe over email] with any questions or comments.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by colin-j-arpe**
## PR Checklist

- [x] Addresses an existing open issue: fixes #37
- [x] That issue was marked as [`status: accepting prs`](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/philly-js-club/philly-js-club-website-remix/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

- Add "contact us" section to About page with a `mailto:` link to Joe's email
- Add new class to `shared.css`, identical to following `<p>` text on page

### CODE REVIEW

**Comment by colin-j-arpe** [comment]
Two notes:
1. #37  had  the heading text with only sentence caps; changed to initial caps to match page style
2. this is my first PR here, so reach out if there's anything I should be doing differently; even if it's minor, if you fix it yourself I'll just make the same mistake again!  You can reach me on the PhillyJS Slack if need be

**Comment by chethtrayen** [comment]
looks good. 

I wish there was a way to show it was clickable. Look like the issue had brackets `You can reach out to [Joe over email] with any questions or comments.` @tjwds any suggestions?
image

**Comment by tjwds** [comment]
@colin-j-arpe This looks great, thanks!  And @chethtrayen, thanks for taking a look; I like that suggestion.

@colin-j-arpe Do you want to add an underline to `a`s within `contact-text`s?  We could do something a bit more general as well, as long as it doesn't have adverse effects on those links with the ↗️ icons.  Up to you!

**Comment by colin-j-arpe** [comment]
Thanks for the feedback.  I went w underlined because I think that's more understood in the web as link style.  I had assumed that the brackets in the issue just implied where to put the link.  Take a look, lemme know if you want it adjusted:
image

I also changed the class name to something more page-wide and made the following section the same.

**Comment by tjwds** [comment]
👍🏻 Looks great, thanks so much!

@all-contributors please add @colin-j-arpe for code

**Pull request merged**
