### PR TITLE
fix: Update font size and line height to vh, resolve #2

### LINKED ISSUE #2: 🐛 Bug: legibility issues when zoomed in
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/philly-js-club-site/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

looks good when zoomed in

### Actual

User reports:

My monitor resolution is 1920x1080 and set at 125%. My browser is at 100%. Chrome says the browser window resolution is 1531 x 721.

The "Code of Contact" text is pretty large and I am seeing divs overlapping each other below.

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by chethtrayen**
## PR Checklist

- [x] Addresses an existing open issue: fixes #002
- [x] That issue was marked as [`status: accepting prs`](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/philly-js-club/philly-js-club-website-remix/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Updated font size and line height to use vh rather than rem. While zooming, the text will not overlap each other and scale accordingly.

### Spec: 
Resolution: 1069x490
Zoom: 200%
image

### CODE REVIEW

**Comment by tjwds** [comment]
This is great!

Is there any way we could make the font sizes a little bit larger?  I like how the blocks of text are a little bit closer to each other on what we currently have in production — it contributes to that brütalist vibe.

**Comment by chethtrayen** [comment]
Updated the size. Let me know if it changes.

**Comment by tjwds** [comment]
Looking good!  I'd suggest we get as close to where we were before as possible, just with the clamps making things look better on atypical screen sizes.  I played around with this and got pretty close, but I'll leave it up to you as to what looks best:

```
-	--font-size-large: clamp(5vh, 5vw, 5.5vh);
+	--font-size-large: clamp(5vh, 5vw, 5.6vh);
 	--font-size-larger: clamp(6vh, 5vw, 9vh);
-	--font-size-title: clamp(11vh, 15vw, 24vh);
+	--font-size-title: clamp(11vh, 15vw, 26vh);
```

Could we reduce the height of `.page-grid-footer` when `(width >= 1000px)` too?  It looks like it makes the "back" link on the code of conduct page a bit hard to click on desktop.

**Comment by chethtrayen** [comment]
I updated the font to be closer to prod. I kept the title size to be smaller because on prod the title is bleeding beyond the mobile size. Also not sure what is the `.page-grid-footer` issue.

image
image

**Comment by tjwds** [comment]
@chethtrayen I think the structure you've put in place is perfect — on my machine, on Chrome, there's a bit of a difference still between production and this branch:

image
image

Are you also seeing that on your end?

**Comment by JoshuaKGoldberg** [comment]
Ping @chethtrayen - is this still something you're interested in?

**Comment by JoshuaKGoldberg** [comment]
Closing out to keep the queue clear in case someone else wants to work on this. LMK if you want to resume! But no worries if you don't have time. 🙂

**Pull request closed without merging**
