### PR TITLE
Tool/handle remix warning, resolve #46

### LINKED ISSUE #46: 🛠 Tooling: resolve Remix serverModuleFormat warning
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

```
⚠️ REMIX FUTURE CHANGE: The `serverModuleFormat` config default option will be changing in v2 from `cjs` to `esm`. You can prepare for this change by explicitly specifying `serverModuleFormat: 'cjs'`. For instructions on making this change see https://remix.run/docs/en/v1.16.0/pages/v2#servermoduleformat
```

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by chethtrayen**
## PR Checklist

- [x] Addresses an existing open issue: fixes #046
- [x] That issue was marked as [`status: accepting prs`](https://github.com/philly-js-club/philly-js-club-website-remix/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/philly-js-club/philly-js-club-website-remix/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Stop Remix build warning. Add `serverModuleFormat: "cjs"` to remix config.

### CODE REVIEW

**Comment by tjwds** [comment]
👍🏻 Thanks!

It looks like there's some extra commits on this branch; let me know if you'd like advice on how to remove those :-)

**Comment by chethtrayen** [comment]
> 👍🏻 Thanks!
> 
> It looks like there's some extra commits on this branch; let me know if you'd like advice on how to remove those :-)

Yes please I have tried and failed.

**Comment by tjwds** [comment]
I think what happened at first was that you had my Remix update branch checked out when you checked out a new branch to make this commit!

So here's how I'd fix it:
* Make sure your copy of main is up to date: `git checkout main; git pull`
* Go back to your branch `git checkout tool/46-handle-remix-warning` (or just `git checkout -`)
* Reset your branch back to main: `git reset --hard main`
* Cherry-pick your change back to the branch: `git cherry-pick cf7c639`
* Push it back up: `git push --force-with-lease`

(There's other ways to approach this, but that's the most straight-forward, imo.)

**Comment by chethtrayen** [comment]
I think it worked?

**Comment by tjwds** [comment]
Thanks for putting this together!

**Pull request merged**
