### PR TITLE
docs: update repo links to philly-js-club repo

### LINKED ISSUE #10: 📝 Documentation: Update docs to point at philly-js-club repo
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/philly-js-club-site/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

The docs link to Josh's repo 🙃 

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by chasenstark**
## PR Checklist

- [ x] Addresses an existing open issue: fixes #10
- [x ] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/philly-js-club-site/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x ] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/philly-js-club-site/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Updates the docs to point at philly-js-club/philly-js-club-website-remix

### CODE REVIEW

**Comment by chasenstark** [comment]
@JoshuaKGoldberg Do you mind sanity checking this one? Thanks!

**Review by JoshuaKGoldberg — APPROVED** [review]
lol yes

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @chasenstark for docs

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @chasenstark for docs

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @chasenstark for docs

**Comment by JoshuaKGoldberg** [comment]
no he didn't

**Comment by JoshuaKGoldberg** [comment]
or, like, it's not on the readme :(

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @chasenstark for docs

**Pull request merged**
